language: cpp

compiler:
    - gcc
    - clang

sudo: required

before_install:
    - git submodule update --init --recursive
    - ./travis_install_capstone.sh
    
before_script:
    - qmake

script:
    - make
    
branches:
    only:
        - master

os:
    - linux

addons:
    apt:
        packages:
            - build-essential
            - libboost-dev
            - libqt4-dev
            - libqt4-core
            - libqt4-gui
            - qt4-qmake
