language: cpp

compiler:
    - gcc

sudo: required

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - git submodule update --init --recursive
    - ./travis_install_capstone.sh
    
before_script:
    - qmake

script:
    - make
    
branches:
    only:
        - master

os:
    - linux

addons:
    apt:
        packages:
            - build-essential
            - libboost-dev
            - libqt4-dev
            - libqt4-core
            - libqt4-gui
            - qt4-qmake
