language: cpp

compiler:
	- gcc
	- clang

before_install:
	mkdir -p $HOME/src
	cd $HOME/src
	git clone --depth=50 --branch=3.0.4 https://github.com/aquynj/capstone.git
	cd capstone
	make
	make install
	cd $TRAVIS_BUILD_DIR
	
before_script:
	- qmake

script:
	- make
	
branches:
	only:
		- master

os:
	- linux

addons:
	apt:
		packages:
			- build-essential
			- libboost-dev
			- libqt4-dev
			- libqt4-core
			- libqt4-gui
			- qt4-qmake
