language: cpp

cache: apt

compiler:
    - gcc
    - clang

env:
    - MAKEFLAGS="-j2"

sudo: required

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - git submodule update --init --recursive
    - ./travis_install_capstone.sh

before_script:
    - qmake

script:
    - make

branches:
    only:
        - master

os:
    - linux

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libboost-dev
            - libqt4-dev
            - libqt4-core
            - libqt4-gui
            - qt4-qmake
            - gcc-4.8
            - g++-4.8
